keys:
  - &users
    - &brian14708 91C32271A5A151D38526881FD03DD6ED48DEE9CE
  - &hosts
    - &aether age1axluheaw8sqntwujvp753xy45uq3a5wuc2qttv7m0p49jcdngaqshw0s93
    - &shiva age1zs59y6dj4tsd3wwq3zds8qlwgsjg4zwn3g5e0cvwfjx0ypd534qsmvtyhv
    - &fuxi age1g6grh79z90kk3pauwgqhlvawdmgwuhwds7rn0hd6k8e70tme958s2suxc0
    - &mbp age13v8s5p9zyvwle0reln03chxkxefwl6l4zn2ellmhcurxu0z6gdqqp7fanc
    - &fujin age16ec47u39azzkgwt2m3mr2qe7vrn6zme32vh2f62zx8samlewe56s0ru8kv
creation_rules:
  # per host
  - path_regex: \/aether\/secrets(\.yaml$|\/)
    key_groups:
      - age:
          - *aether
        pgp: *users
  - path_regex: \/shiva\/secrets(\.yaml$|\/)
    key_groups:
      - age:
          - *shiva
        pgp: *users
  - path_regex: \/fuxi\/secrets(\.yaml$|\/)
    key_groups:
      - age:
          - *fuxi
        pgp: *users
  - path_regex: \/mbp\/secrets(\.yaml$|\/)
    key_groups:
      - age:
          - *mbp
        pgp: *users
  - path_regex: \/fujin\/secrets(\.yaml$|\/)
    key_groups:
      - age:
          - *fujin
        pgp: *users
  # infra
  - path_regex: ^infra\/(.*\.)?secrets\.yaml$
    key_groups:
      - age: *hosts
        pgp: *users
