keys:
  - &users
    - &brian14708 91C32271A5A151D38526881FD03DD6ED48DEE9CE
  - &hosts
    - &aether age1njv0p36yayjk0zts7e0pzzlw6kpppfydk0ue0p9e944x0025gdkses23w3
    - &shiva age1zs59y6dj4tsd3wwq3zds8qlwgsjg4zwn3g5e0cvwfjx0ypd534qsmvtyhv
    - &fuxi age1g6grh79z90kk3pauwgqhlvawdmgwuhwds7rn0hd6k8e70tme958s2suxc0
    - &mbp age13v8s5p9zyvwle0reln03chxkxefwl6l4zn2ellmhcurxu0z6gdqqp7fanc
creation_rules:
  - path_regex: \/aether\/(.*\.)?secret\.yaml$
    key_groups:
      - age:
          - *aether
        pgp: *users
  - path_regex: \/shiva\/(.*\.)?secret\.yaml$
    key_groups:
      - age:
          - *shiva
        pgp: *users
  - path_regex: \/fuxi\/(.*\.)?secret\.yaml$
    key_groups:
      - age:
          - *fuxi
        pgp: *users
  - path_regex: \/mbp\/(.*\.)?secret\.yaml$
    key_groups:
      - age:
          - *mbp
        pgp: *users
  - path_regex: \/common\/(.*\.)?secret\.yaml$
    key_groups:
      - age: *hosts
        pgp: *users
  - path_regex: ^infra\/(.*\.)?secret\.yaml$
    key_groups:
      - age: *hosts
        pgp: *users
